name: webdav_lastsync

on: [push]

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: |
          export SYNCFILE="lastsync.txt"
          export REMOTEFILE="https://dav.jianguoyun.com/dav/zotero/lastsync.txt"
          touch ${SYNCFILE}
          curl -u ${JIANGUOYUN_EMAIL}:${JIANGUOYUN_DAVPASS} -T ${SYNCFILE} ${REMOTEFILE}
        env:
          JIANGUOYUN_EMAIL: ${{ secrets.JIANGUOYUN_EMAIL }}
          JIANGUOYUN_DAVPASS: ${{ secrets.JIANGUOYUN_DAVPASS }}