name: webdav_lastsync

on: [push]

jobs:
  fix:
    runs-on: ubuntu-18.04
    steps:
      - name: Fix
        env:
          JIANGUOYUN_EMAIL: ${{ secrets.JIANGUOYUN_EMAIL }}
          JIANGUOYUN_DAVPASS: ${{ secrets.JIANGUOYUN_DAVPASS }}
        run: |
          touch lastsync.txt
          curl -u ${JIANGUOYUN_EMAIL}:${JIANGUOYUN_DAVPASS} -T lastsync.txt https://dav.jianguoyun.com/dav/zotero/lastsync.txt
