name: webdav_lastsync

on: [push]

jobs:
  fix:
    runs-on: ubuntu-18.04
    steps:
      - name: Fix
        env:
          JIANGUOYUN_EMAIL: ${{ secrets.JIANGUOYUN_EMAIL }}
          JIANGUOYUN_DAVPASS: ${{ secrets.JIANGUOYUN_DAVPASS }}
        run: |
          export SYNCFILE="lastsync.txt"
          export REMOTEFILE="https://dav.jianguoyun.com/dav/zotero/${SYNCFILE}"
          touch ${SYNCFILE}
          curl -u ${JIANGUOYUN_EMAIL}:${JIANGUOYUN_DAVPASS} -T ${SYNCFILE} ${REMOTEFILE}
